# Note: sidekiq_boot.rb is loaded via config/environment.rb which Sidekiq loads by default
# when started with `bundle exec sidekiq`. We configure eager loading there.
:require: ./config/environment.rb
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
:timeout: 45

:queues:
  - internal
  - default
  - mail

staging:
  :concurrency: 10

production:
  :concurrency: 20
