db:
  name: cvgen_web_test
secret_key_base: cefa44e98a8be9dcdf6e56c88e7bc1ed3a8fb2a6c3cbf12806d098137799216263ff68847eaf65d43e5274997f39da87ffa5f247de814afe16bc819bf46b77c7
chat_gpt_api_key: test-openai-key
oauth:
  google:
    client_id: test-google-id
    client_secret: test-google-secret
  apple:
    client_id: test.apple.client
    team_id: TESTTEAM
    key_id: TESTKEYID
    private_key: test
  facebook:
    app_id: test-facebook-id
    app_secret: test-facebook-secret
  linkedin:
    client_id: test-linkedin-id
    client_secret: test-linkedin-secret
